name: Verify YAML files

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        pip install -r tests/requirements-tests.txt
    - name: Run schema tests
      run: |
        py.test --disable-warnings tests/test_schema.py
    - name: Run ids tests
      run: |
        py.test --disable-warnings tests/test_ids.py
